# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.1"

default_platform :ios

COMMIT_MESSAGE = "Bump podspec to"

platform :ios do
    lane :release do |options|
      version_number = options[:version_number]

      sh("git checkout develop")
      ensure_git_branch(branch: 'develop') # make sure that we are on develop branch

      version = version_bump_podspec(path: "AmazonFling.podspec", version_number: version_number)

      pod_lib_lint(allow_warnings: false, sources: ["https://github.com/CocoaPods/Specs.git"])

      git_commit(path: ["./AmazonFling.podspec", "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
      push_to_git_remote(remote_branch: 'develop', force: false, tags: true)

      sh("git checkout master")
      sh("git merge develop")

      add_git_tag(tag:"#{version}")
      sh("git push origin master --tags")

      sh("git fetch --tags")
      pod_push(path: "AmazonFling.podspec", allow_warnings: false)
    end
end
